apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phpmyadmin
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: phpmyadmin
    spec:
      project: default
      source:
        repoURL: oci://tccr.io/truecharts/phpmyadmin
        chart: phpmyadmin
        targetRevision: "8.3.0"  # pin this version for stability
        helm:
          values: |
            backend:
              host: 172.19.39.3
            service:
              type: LoadBalancer
              loadBalancerIP: 172.19.50.128
      destination:
        server: https://kubernetes.default.svc
        namespace: phpmyadmin
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 1m # the maximum amount of time allowed for the backoff strategy
