apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - clusters: {}
  project: default
  source:
    path: apps
    repoURL: https://github.com/merclangrat/kubetest
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
