apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: curator-workflow
spec:
  goTemplate: true
  generators:
    clusters: {}
  template:
    goTemplate: true
    metadata:
      name: curator-workflow
    spec:
      project: default
      source:
        repoURL: https://github.com/merclangrat/kubetest.git
        targetRevision: HEAD
        path: manifests/curator
        directory:
          recurse: true
      destination:
        namespace: argo-workflows
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
