apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curator-workflow
  namespace: argocd  # This stays as argocd, where ArgoCD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/merclangrat/kubetest.git
    path: manifests/curator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
