apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: argo-cron-workflows-test
  namespace: argo-workflows
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 30
  workflowSpec:
    entrypoint: test
    templates:
    - name: test
      container:
        image: google/cloud-sdk:latest
        command: ["ls", "-al", "/etc"]
        imagePullPolicy: Always
        volumeMounts:
        - name: test-serviceaccount
          mountPath: /etc/serviceaccount.json
          subPath: serviceaccount.json
      volumes:
        - name: test-serviceaccount
          configMap:
            name: test-serviceaccount
            items:
              - key: serviceaccount.json
                path: serviceaccount.json
