apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: argo-cron-workflows-test
  namespace: argo-workflows
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 30
  workflowSpec:
    entrypoint: test
    templates:
    - name: test
      container:
        image: google/cloud-sdk:latest
        command: ["bash", "/script/gcloud_cleaner.sh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: serviceaccount
          mountPath: /config/serviceaccount.json
          subPath: serviceaccount.json
        - name: gcloudcleaner
          mountPath: /script/gcloud_cleaner.sh
          subPath: gcloud_cleaner.sh
      volumes:
        - name: serviceaccount
          Secret:
            name: serviceaccount
            items:
              - key: serviceaccount.json
                path: serviceaccount.json
        - name: gcloudcleaner
          configMap:
            name: gcloudcleaner
            items:
              - key: gcloud_cleaner.sh
                path: gcloud_cleaner.sh
