apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: argo-cron-workflows-test
  namespace: argo-workflows
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 30
  workflowSpec:
    entrypoint: test
    templates:
    - name: test
      container:
        image: google/cloud-sdk:latest
        command: ["ls", "-alR", "/opt"]
        imagePullPolicy: Always
      env:
       - name: PRIVATE_KEY_ID
         valueFrom:
           secretKeyRef:
             name: marketing-service-account
             key: private_key_id
       - name: PRIVATE_KEY
         valueFrom:
           secretKeyRef:
             name: marketing-service-account
             key: private_key
      volumeMounts:
        - name: gcloudcleaner
          mountPath: /opt/gcloud_cleaner.sh
          subPath: gcloud_cleaner.sh
      volumes:
        - name: gcloudcleaner
          configMap:
            name: gcloudcleaner
