apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: argo-cron-workflows-test
  namespace: argo-workflows
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 30
  workflowSpec:
    entrypoint: test
    templates:
    - name: test
      container:
        image: google/cloud-sdk:latest
        command: ["bash", "/script/gcloud_cleaner.sh"]
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          value: 'marketing-pages-master-172637'
        - name: CLIENT_ID
          value: '102033659470860074900'
        - name: PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              name: marketing-service-account
              key: private_key_id
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: marketing-service-account
              key: private_key
        volumeMounts:
          - name: gcloudcleaner
            mountPath: /script/gcloud_cleaner.sh
            subPath: gcloud_cleaner.sh
      volumes:
        - name: gcloudcleaner
          configMap:
            name: gcloudcleaner
