apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: argo-cron-workflows-test
  namespace: argo-workflows
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 30
  workflowSpec:
    entrypoint: test
    templates:
    - name: test
      container:
        image: google/cloud-sdk:latest
        command: ["ls", "-al", "/etc"]
        imagePullPolicy: Always
        configs:
        - mountpath: /etc
          files:
            - name: serviceaccount.json
              data: |
                {
                  "type": "service_account",
                  "project_id": "demo"
                  "private_key_id": "demo"
                  "private_key": "demo"
                  "client_email": "demo@appspot.gserviceaccount.com",
                  "client_id": "998712784766"
                  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                  "token_uri": "https://oauth2.googleapis.com/token",
                  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/demo%40appspot.gserviceaccount.com",
                  "universe_domain": "googleapis.com"
                }
