apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-lb
  namespace: phpmyadmin
  labels:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 172.19.50.128   # your desired IP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/instance: phpmyadmin
