apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'argo-workflows'
    spec:
      project: default
      source:
        repoURL: 'https://argoproj.github.io/argo-helm'
        targetRevision: '0.45.19'
        chart: argo-workflows
        helm:
          values: |
            controller:
              workflowNamespaces:
                - "argo-workflows"
            server:
              extraArgs:
                - --auth-mode=server
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argo-workflows'
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 0
