apiVersion: v1
kind: ConfigMap
metadata:
  name: gcloudcleaner
  namespace: argo-workflows
data:
  gcloud_cleaner.sh: |
    #!/bin/bash
    cat >/script/serviceaccount.json <<EOL
    {
      "type": "service_account",
      "project_id": "${PROJECT_ID}",
      "private_key_id": "${PRIVATE_KEY_ID}",
      "private_key": "${PRIVATE_KEY}",
      "client_email": "${PROJECT_ID}@appspot.gserviceaccount.com",
      "client_id": "${CLIENT_ID}",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/${PROJECT_ID}%40appspot.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
    EOL
    
    SAVE_VERSION_COUNT=5
    # Authentication
    gcloud auth activate-service-account ${PROJECT_ID}@appspot.gserviceaccount.com --key-file=/script/serviceaccount.json --project=${PROJECT_ID}
    # GET SERVICES NAME
    SERVICES=$(gcloud app versions list   --sort-by '~VERSION.ID'   --format 'value(SERVICE)'|sort|uniq)
    for service in $SERVICES; do
            echo "############# WILL BE DELTED FOR $service #######################"
            gcloud app versions list  --service $service --format="value(version.id)" --sort-by="~version.createTime" | tail -n +$SAVE_VERSION_COUNT
    done
