apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: curator-prod-workflow
spec:
  schedule: "18 4 * * *"
  timezone: "UTC"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 30
  workflowSpec:
    entrypoint: curator-job
    podMetadata:
      labels:
        app: curator
    templates:
    - name: curator-job
      container:
        image: untergeek/curator:8.0.21
        imagePullPolicy: IfNotPresent
        command: ["/curator/curator"]
        args:
          - "--hosts"
          - "http://172.19.4.1:9202"
          - "/etc/curator/action.yml"
        volumeMounts:
        - name: curator-config
          mountPath: /etc/curator
    volumes:
    - name: curator-config
      configMap:
        name: '{{ .name }}-config'
