apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
data:
  action.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Delete pymlsapi older than 7 days"
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: pymlsapi-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
          exclude:
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: curator-cleanup
spec:
  schedule: "{{schedule}}"
  timezone: "UTC"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 30
  workflowSpec:
    entrypoint: curator-job
    podMetadata:
      labels:
        app: curator
    templates:
    - name: curator-job
      container:
        image: untergeek/curator:8.0.21
        imagePullPolicy: IfNotPresent
        command: ["/curator/curator"]
        args:
          - "--hosts"
          - "{{host}}"
          - "/etc/curator/action.yml"
        volumeMounts:
        - name: curator-config
          mountPath: /etc/curator
    volumes:
    - name: curator-config
      configMap:
        name: curator-config
