apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp-dynamic-env
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  generators:
    - scmProvider:
        gitea:
          owner: traxess
          api: https://git.traxess.eu/
          allBranches: true
          tokenRef:
            secretName: gitea-token
            key: token
        cloneProtocol: https
        filters:
          - repositoryMatch: ^kubernetes$
            branchMatch: ^[A-Z]+-\d+/[a-zA-Z-]+/[a-zA-Z0-9]+(?:/([a-zA-Z0-9]+))?$
        requeueAfterSeconds: 300
  template:
    metadata:
      labels:
        app: kubetest-dev
      name: 'w-{{ (trunc 8 .sha) }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/paulbouwer/hello-kubernetes.git'
        targetRevision: HEAD
        path: deploy/helm/hello-kubernetes
        helm:
          valueFiles:
          - values.yaml
          values: |
            message: 'Tervetuloa! Olen haara {{.branch}}, seikka on {{ (split "/" .branch)._0 }} !'
            deployment:
              replicaCount: 1
      destination:
        server: https://kubernetes.default.svc
        namespace: webapp-dynamic-env
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:
          - CreateNamespace=true
#      ignoreDifferences:
#        - group: apps
#          kind: Deployment
#          jsonPointers:
#            - /spec/replicas
