apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
  loadBalancerIP: 172.19.50.111
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
